# Generated by Django 4.2.11 on 2025-06-26 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terminals', '0002_terminal_created_at_terminal_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='terminals.terminal')),
            ],
        ),
    ]
